name: Ethereal
description: Sharing knowledges of Programing
encoding: utf-8

locale: en-US
timezone: Asia/Rangoon # alias Asia/Yangon

# theme: jekyll-theme-slate

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      layout: "master"
